### PR TITLE
Fix for issue no. 55 and no. 45

### PR DESCRIPTION
**Pull request by rich-ard**
This corrects the issue arising when special characters are stripped from search terms in situations when the search results take more than a single page to display.

### CODE REVIEW

**Comment by fmoliveira** [comment]
Hey Richard, why is the PR closed without merging?

**Comment by fmoliveira** [comment]
Adding links to #45 and #55.

**Comment by fmoliveira** [comment]
Hey @rich-ard , why is the PR closed without merging?

**Comment by rich-ard** [comment]
Because I made a couple of edits to the readme.md file (including installation notes) that broke its formatting and didn't intend them to push. I've reopened the pull request and can fix the readme file in the next day or two. Sorry, getting used to using git. :)

**Comment by fmoliveira** [comment]
I see @rich-ard , it happened to me too. :)

I was just worried that it was accidentaly closed and your work wouldn't be merged. Don't worry, take the time you need it. :smile: :+1:

**Comment by rich-ard** [comment]
Once I have the readme file repaired from my clumsy editing, I'll send a second pull request to follow this one.

**Comment by rich-ard** [comment]
Got it, sir. Please see the current request(s) :)

On Wed, Jan 14, 2015 at 8:32 AM, Filipe Oliveira <notifications@github.com>
wrote:

> I see @rich-ard <https://github.com/rich-ard> , it happened to me too. :)
>
> I was just worried that it was accidentaly closed and your work wouldn't
> be merged. Don't worry, take the time you need it. [image: :smile:] [image:
> :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deleteman/lfpr/pull/57#issuecomment-69916005>.
>



-- 
--

Richard Tyler Brandt
rtbrandt@gmail.com

**Comment by fmoliveira** [comment]
Great! Now just let's wait for @deleteman  to review it. :+1:

**Comment by deleteman** [comment]
Merged and deployed, althought issue #55 is not 100% fixed.

**Comment by fmoliveira** [comment]
:+1:

**Pull request merged**
